### ISSUE TITLE
Edit multiple files at once

### ISSUE THREAD

**Issue by jukos** [citygml4j/citygml-tools#13]
Hello,
I use the cityGML data of hamburg:
http://suche.transparenz.hamburg.de/dataset/3d-stadtmodell-lod2-de-hamburg2

I have no problems to convert a xml file to a cityjson file. For example:
C:\citygmltools\citygml-tools-1.3.2\bin>.\citygml-tools to-cityjson C:\citygmltools\hamburg\LoD2_558_5935_1_HH.xml

But I have many xml files. 
It is possible to edit several files a once? Or all files within the folder hamburg?
If yes, how, with which command?

Greetings

**Comment by mwussow** [comment]
Hi jukos,

yes, this is possible: you just need to provide the path to the folder where all the files that you want to convert are stored instead of providing the path of a specific file within that folder. In your case the following line should do the magic:

`.\citygml-tools to-cityjson C:\citygmltools\hamburg\`

There seems to be one caveat though: do not try to convert too many files at once, else you likely run out of java heap space and file sizes blow up (I guess this is a bug in citygml-tools)

**Comment by clausnagel** [comment]
In addition to the answer of @mwussow, `citygml-tools` also supports glob patterns to specify your set of input files.

**Comment by clausnagel** [comment]
Just published version [1.4.0](https://github.com/citygml4j/citygml-tools/releases/tag/v1.4.0) which contains a fix for #14 mentioned by @mwussow. So closing this issue.
