### ISSUE TITLE
The conversion to JSON is incorrect.

### ISSUE THREAD

**Issue by gtk2k** [citygml4j/citygml-tools#19]
https://raw.githubusercontent.com/gtk2k/CityGMLsampleData/main/53392559_bldg_6697_op2.gml

Converting this file to json doesn't specifically convert the value of posList.

**Comment by clausnagel** [comment]
By default, the `to-cityjson` command only keeps three digits after the decimal point for geometry vertices. Since you use geographic coordinates in your dataset, the vertices are mapped to just two distinct points when considering only three digits. Thus, you need to increase this value.

General overview of the `to-cityjson` command with its options and their default values:

    $ citygml-tools to-cityjson -h

Example command to convert your dataset

    $ citygml-tools to-cityjson --vertices-digits=14 53392559_bldg_6697_op2.gml

Also note that the i-UR ADE is not supported by citygml-tools and, thus, all elements associated with the namespace  `http://www.kantei.go.jp/jp/singi/tiiki/toshisaisei/itoshisaisei/iur/uro/1.4` are ignored in the conversion. If there was a target CityJSON schema for the i-UR ADE, I could think of adding support for it.

**Comment by gtk2k** [comment]
thanx
