### ISSUE TITLE
Warning when using non standard XML tags of CityGML

### ISSUE THREAD

**Issue by leoleynse** [citygml4j/citygml-tools#26]
Hello,

I tried to use citygml-tools to convert the Dutch BGT-files (CityGML-files from PDOK) to CityJSON-files. Unfortunately the output-files didn't have a useful outcome. Reason appeared to be the fact that the PDOK files weren't "vanilla" CityGML files; they contain an ADE.

It would be nice if you got a warning using "non-vanilla" files. Is it possible to implement this option?

Regards,

Leo

**Comment by clausnagel** [comment]
Thanks for reporting. Sounds like a reasonable enhancement to have a warning as proposed.

I am not aware of PDOK. Is this ADE publically available?

**Comment by leoleynse** [comment]
PDOK (www.pdok.nl) is the Dutch portal for open geo datasets of the government. The BGT-files (topo info) use the extra features of the IMGeo ADE (https://docs.geostandaarden.nl/imgeo/catalogus/imgeo/).

**Comment by romanzaw** [comment]
Hello, 

I want to ask about my research, which is about converting IFC data to CityGML and CityJSON formats for 3D Cadastre.

I'm having problem converting citygml model to cityjson using citygml tools. The citygml model I got from converting the ifc model on the fzk viewer. The ifc elements I convert to citygml are ifc space and ifc wall. But when I convert it to a cityjson model, the space element doesn't appear in the ninja cityjson viewer. Can you explain why this can happen? does cigyjson not support space elements represented in lod4solid model? because the wall element can still appear (wall element in lod2MultiSurface). here I attach the citygml and cityjson files

Best Regards

Romanza
[cobacoba_2.zip](https://github.com/citygml4j/citygml-tools/files/8801360/cobacoba_2.zip)
[cobacoba_2.zip](https://github.com/citygml4j/citygml-tools/files/8801367/cobacoba_2.zip)

**Comment by clausnagel** [comment]
citygml-tools uses CityJSON 1.0 as target, which does neither support rooms nor LoD4 geometries (see the [spec here](https://www.cityjson.org/specs/1.0.3/)) . Your spaces are not contained in the CityJSON output because they are converted to CityGML LoD4 rooms. This issue cannot be solved easily because in CityGML 2.0 you can only represent rooms in LoD4.

**Comment by romanzaw** [comment]
but when I convert the citygml model to cityjson generated from FME, the model can be rendered completely (including space elements represented in LOD4 MultiSurface) in cityjson web viewer. Is the version of cityjson used by FME different from citygml tools?

**Comment by romanzaw** [comment]
![gambar](https://user-images.githubusercontent.com/75918942/171107738-ba0d3426-cd5c-4903-88a7-d1aae6473f77.png)
![gambar](https://user-images.githubusercontent.com/75918942/171109250-c0e6801c-023e-4970-b668-2d0725404c5e.png)
![gambar](https://user-images.githubusercontent.com/75918942/171109509-9e4fb423-6890-4e2f-b5e8-e71b35041b27.png)


the following is proof that the citygml model converted from fme cannot be converted to cityjson in citygml tools, while on fme I can convert citygml to cityjson

Also in first picture, I converted the ifc model into citygml with 3 different software, namely evebim, fme, and fzk. But when I'm going to validate the xml model citygml generated by fme, the citygml tools display says "0 found cityobjects" (still in the image). What does this message mean? even though the xml validation of the citygml model generated by evebim and fzk can be done without any error messages

**Comment by romanzaw** [comment]
regarding the problem "Found 0 file(s) at.....", how to solve the problem? so that my citygml xml file can be validated

**Comment by clausnagel** [comment]
Provide the correct path + filename to your CityGML file. If you just provide a filename without a path, then citygml-tools searches the file in the current working directory by default. If this still doesn't work, try and get rid of the special characters (`[`, `]`, `#`) in the filename.

**Comment by romanzaw** [comment]
it's true that after I renamed the file by deleting the character as you said, I can now validate my citygml file. Thanks very much for your help.

But I want to ask again, about converting citygml to cityjson, I still can't see the feature when loaded into the cityjson ninja web viewer, even though citygml tools can convert it to cityjson ? does cityjson also not support representation of citygml elements if modeled in lod4multisurface ? (my citygml file is lod4multisurface). I still can't understand the cityjson specs regarding LOD representation in cityjson

**Comment by romanzaw** [comment]
OK I will re-read resource that related to this. 

Next, let me ask again about what you said that mapping Room elements to Building Parts is something that is not true from a semantic point of view. What is the meaning of this statement? because I got the CityGML to Cityjson conversion scheme from :
https://community.safe.com/s/question/0D54Q000080hfvVSAQ/problem-with-conversion-of-citygml-to-json

in addition, fme also provides cityjson model results that can be displayed in the ninja viewer

**Comment by romanzaw** [comment]
sorry if I ask this to you, because I have asked KIT developer as a developer of FZK viewer but I haven't received a response. I thought maybe you understand my problem

I have 2 questions about fzk viewer as follows:

1. I converted ifcspace to room on fzk, then I checked that this software can be used to calculate the volume of objects modeled in gml:solid (one of which is the interior of the room). On the other hand, I have room interior volume data from all ifcspace elements that I converted. The volume data is the result of the size of the 3D model which is formed from the data as built drawing before the 3D model is exported into ifc format. Next I try to compare the volume of the ifc 3D model and the volume of the 3D model after ifcspace was converted to a Room (citygml element). As a result, there are several rooms that have different volume values with the volume of the ifc 3D model that formed from the as built drawing (this data is considered as the correct volume). Why did it happen ? shouldn't the volume in the citygml model be the same as the ifc volume ? 

2. As we know that in order to calculate the volume of a room element, it must be modeled in gml:solid. However I found there are 2 features in the Room element which I converted from ifcspace, modeled in lod4MultiSurface. Why does this happen ? even though the other rooms are modeled in lod4solid

Best Regards

**Comment by clausnagel** [comment]
> It would be nice if you got a warning using "non-vanilla" files. Is it possible to implement this option?

I added a warning if a input file contains unsupported non-CityGML content (see [here](https://github.com/citygml4j/citygml-tools/commit/e6bcbe9e4c3be9f2015154c71d63b1ff2535e942)). This will be released with the next major version 2.0 of citygml-tools. Closing this issue.
