### ISSUE TITLE
Problems with CityJson file converted from citygml 

### ISSUE THREAD

**Issue by nimafo** [citygml4j/citygml-tools#30]
I am trying to convert citygml files generated with [`Random3Dcity`](URL). It is a tool developed for procedurally generating 3D city models. It generates also models for interiors in 4 LoDs (0, 1, 2-2, 2-3).
the problem is that after conversion to CityJson:
1. the geometry in `InteriorLoD2-2` and `InteriorLoD2-3` is not maintained.
2. `InteriorLoD0 ` and `InteriorLoD1` contain geometry, according to `val3dity `,  while`InteriorLoD1` is valid, `InteriorLoD1` has the following problems: 

> - [104](https://val3dity.readthedocs.io/en/latest/errors/#ring-self-intersection): Ring_self_intersection
> - [303](https://val3dity.readthedocs.io/en/latest/errors/#non-manifold-case): Non_Manifold_case
> - [307](https://val3dity.readthedocs.io/en/latest/errors/#polygon-wrong-orientation): Polygon_wrong_orientation

when I redo the conversion with `--vertex-precision=20`, `val3dity ` gives: 

> 102- [CONSECUTIVE_POINTS_SAME](https://val3dity.readthedocs.io/en/latest/errors/#consecutive-points-same)

 both for InteriorLoD0 and 1. I did it again with `--vertex-precision=10` and `--vertex-precision=15`, which resulted in the same error for LoD1 I mentioned above(104, 303, 307). 

3. For `InteriorLoD2-2` and `InteriorLoD2-3` no geometries are maintained after conversion (error [609](https://val3dity.readthedocs.io/en/latest/errors/#cityobject-has-no-geometry)). 
4. For `LoD3`, not only there is missing geometry for some building installations, but also errors [102: Consecutive points same](https://val3dity.readthedocs.io/en/latest/errors/#consecutive-points-same) and [201: Intersection rings](https://val3dity.readthedocs.io/en/latest/errors/#intersection-rings).

**Validation of gmls**
When validating geometries in 3DCityDB, for all of the 5 files I get the following errors: 

> - Invalid content

The complete description [here](https://www.dropbox.com/s/i4q2hhe68ru7i2n/errors_3DcityDB.txt?dl=0). and

> - '7a7cae4a-d090-4c0c-922f-a29aea3e5c26' is not a valid value for 'NCName' 

**Other**
- When converting with `citygml-tools`, I get the following warning: 
> The input file uses unsupported non-CityGML namespace(s): http://www.safe.com/xml/xmltables.
- This is the line of code I use for the conversion: 
- `.\citygml-tools to-cityjson --vertex-precision=20 "path\to\gmls"\*.gml `. as mentioned above, I also did test `--vertex-precision=3` which I think is the default value, `--vertex-precision=10`, and `--vertex-precision=15`. 
Is this the related to the above error about invalid 'NCName'?
- You can download the 5 gml files and converted cityjson ones generated from this package, including the mentioned 4 LoDs for interior and one exterior LoD3.0 file [here in this link](https://www.dropbox.com/s/fis12lq3o9fd9kg/Citygml-tools_Random3Dcity_Conversion_github_issue.rar?dl=1).
- I am using `citygml-tools, version 2.0.0-rc.1 `

**Comment by clausnagel** [comment]
Thanks, @nimafo, for opening an issue. We need more information though to be able to reproduce and work on the issue.

- What dataset are you trying to convert?
- What error message is thrown by citygml-tools?
- Which version of citygml-tools are you using?
- What command-line options do you use when invoking citygml-tools?

**Comment by clausnagel** [comment]
Can you please verify your download link? I am only able to download the `errors_3DcityDB.txt` file but not the CityGML input datasets.

**Comment by nimafo** [comment]
@clausnagel I updated the link, I think it should work now. 
Sorry for this.

**Comment by clausnagel** [comment]
Thanks, the download works now. I validated your .gml files against the CityGML schemas and _all of them_ are _invalid_. You can easily validate the files yourself using the `validate` command of citygml-tools (use version [2.0.0](https://github.com/citygml4j/citygml-tools/releases/tag/v2.0.0) rather than 2.0.0-rc.1). Some errors and findings:

**interior-LOD0.gml**
- The buildings have multiple `<bldg:lod1MultiSurface>` geometry properties where only one is allowed. No wonder that this leads to geometry errors.  
- Many objects have invalid `gml:id` values. The allowed values for `gml:id` are strictly defined in the XML world (see [`xs:ID`](https://www.oreilly.com/library/view/xml-schema/0596002521/re74.html) and [`xs:NCName`](https://www.oreilly.com/library/view/xml-schema/0596002521/re82.html)). For instance, a `gml:id` must not start with a number. 
- Invalid order of elements
- Note that despite its name the file does _not_ contain LoD0 geometries but only LoD1 geometries. Also note that CityGML 2.0 _only supports interior details in LoD4_.

**interior-LOD1.gml**
- Invalid `gml:id` values and invalid order of elements.
- No LoD1 geometries but only LoD2 geometries.
- Many of the solids in the CityGML file have geometry errors. I used `CityDoctor` v3.12.1 for geometry validation rather than `val3dity`. So, no wonder that there are also geometry errors in the CityJSON output.

**interior-LOD2_2.gml**
- Invalid `gml:id` values and invalid order of elements.
- The `<bldg:lod2Solid>` properties contain `gml:MultiSolid` geometries which are _not allowed_ here. Only `gml:Solid` or `gml:CompositeSolid` are allowed. That's why the geometries of the buildings cannot be parsed by citygml-tools and hence are not converted to CityJSON.

**interior-LOD2_3.gml**
- Same problems as identified for interior-LOD2_2.gml.

**LOD3_0.gml**
- Invalid `gml:id` values and invalid order of elements.
- I do not see missing geometries for building installations. I visualized the CityGML file with `FZKViewer` and the CityJSON output with the `ninja` web viewer but could not spot a difference. Maybe you can point me to the missing geometries using a screenshot? 
- Again, `CityDoctor` already reports invalid geometries for the CityGML file. So, no wonder that there are also geometry errors in the CityJSON output. You might check whether a smaller value for `snap_tol` makes a difference when validating with `val3dity`.

To make a long story short: Your CityGML input files have many issues and are invalid. There is no way for citygml-tools to convert them to clean and valid CityJSON files. So, I see no immediate action for citygml-tools. It rather seems that Random3Dcity needs some fixing.

**Comment by nimafo** [comment]
@clausnagel This is great, thanks a lot for your thorough review of the files.
