### ISSUE TITLE
translation when export to cityjson possibly not correct?

### ISSUE THREAD

**Issue by pcace** [citygml4j/citygml-tools#37]
Hi, this is possibly related to #36, but i just cannot figure out what is wrong when exporting citygml to cityjson. i am trying to export these files here (*.xml): 
https://cloud.johannes-froelich.de/s/xtwyW4rrNoeZTE5
When viewing the xml verything looks fine -> 
![image](https://user-images.githubusercontent.com/1011875/212073502-ab78a327-3be6-4664-ae86-9a6aebba2dc4.png)

BUT: when looking at the exported cityJSON, they are wrong on the y axis: 
![212029721-e42a87e0-4fb0-48fd-9e91-2bba438b8f95](https://user-images.githubusercontent.com/1011875/212073822-76d538a1-289d-4752-a689-3904c5bd0359.png)

removing the translate section from the resulting cityjson files overlays the 3d Data in x direction but not in y. 
![image](https://user-images.githubusercontent.com/1011875/212074127-aaa73fa3-e521-4d0c-9194-78cc58341762.png)

i just cannot figure out where the problem is - or what the logic is... 
Thanks a lot for help or ideas what and where the problem could be!

**Comment by clausnagel** [comment]
Have you checked whether you maybe run into the same issue as described in #31? The bug is fixed in master but the bugfix is not contained in the latest release yet. Please use the `edge` Docker image of citygml-tools from [Docker Hub](https://hub.docker.com/r/citygml4j/citygml-tools) to test. This Docker image already contains the bugfix.

**Comment by pcace** [comment]
uff thank you so much! works as expected now!
