### ISSUE TITLE
Upgrade option removes geometry element for LOD 4

### ISSUE THREAD

**Issue by RushiHFT** [citygml4j/citygml-tools#42]
Hi,

I recently faced an issue while using Upgrade command with CityGML 2.0 LOD 4 building . The output version 3.0 file does not contain any geometry elements. It works fine with LOD 2 buildings.

I look forward to your feedback. 

Thanks and best regards,
Rushi

**Comment by clausnagel** [comment]
I'd say it works as expected because there is no LoD4 in CityGML 3.0 anymore. For this reason, the `upgrade` command offers the option `--use-lod4-as-lod3` (or just `-u`). Use this option in your command to map the LoD4 to LoD3 in the CityGML 3.0 output file. If your input file also contains an LoD3, it will be overwritten though.

**Comment by RushiHFT** [comment]
Perfect thank you so much :-)
